### ISSUE TITLE
可以在vue3上面使用吗？

### ISSUE THREAD

**Issue by yangcanlin** [lete114/API-Interface#3]
貌似好像报错

**Comment by lete114** [comment]
?

**Comment by yangcanlin** [comment]
![image](https://github.com/Lete114/API-Interface/assets/76166196/452274dc-f747-4427-b82a-f8a687949f88)
![image](https://github.com/Lete114/API-Interface/assets/76166196/9bd36dad-a5d2-4060-abe3-92c8765f715a)

**Comment by lete114** [comment]
这是一个nodejs服务，不能在浏览器中运行
